<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 1 Burial data | Cultural hitchhiking: burial rites and genomic variation in space and time</title>
  <meta name="description" content="Chapter 1 Burial data | Cultural hitchhiking: burial rites and genomic variation in space and time" />
  <meta name="generator" content="bookdown 0.43 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 1 Burial data | Cultural hitchhiking: burial rites and genomic variation in space and time" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 1 Burial data | Cultural hitchhiking: burial rites and genomic variation in space and time" />
  
  
  

<meta name="author" content="Elisabetta Canteri" />


<meta name="date" content="2025-07-04" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="aim.html"/>
<link rel="next" href="burial-rites.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Cultural hitchhiking: burial rites and genomic variation in space and time</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Abstract</a></li>
<li class="chapter" data-level="" data-path="aim.html"><a href="aim.html"><i class="fa fa-check"></i>Aim</a></li>
<li class="chapter" data-level="1" data-path="burial-data.html"><a href="burial-data.html"><i class="fa fa-check"></i><b>1</b> Burial data</a>
<ul>
<li class="chapter" data-level="1.1" data-path="burial-data.html"><a href="burial-data.html#data-table"><i class="fa fa-check"></i><b>1.1</b> Data table</a></li>
<li class="chapter" data-level="1.2" data-path="burial-data.html"><a href="burial-data.html#histograms"><i class="fa fa-check"></i><b>1.2</b> Histograms</a></li>
<li class="chapter" data-level="1.3" data-path="burial-data.html"><a href="burial-data.html#temporal-patterns"><i class="fa fa-check"></i><b>1.3</b> Temporal patterns</a></li>
<li class="chapter" data-level="1.4" data-path="burial-data.html"><a href="burial-data.html#spatiotemporal-patterns"><i class="fa fa-check"></i><b>1.4</b> Spatiotemporal patterns</a></li>
<li class="chapter" data-level="1.5" data-path="burial-data.html"><a href="burial-data.html#adding-ancestry-and-mobility"><i class="fa fa-check"></i><b>1.5</b> Adding ancestry and mobility</a>
<ul>
<li class="chapter" data-level="1.5.1" data-path="burial-data.html"><a href="burial-data.html#radius-approach"><i class="fa fa-check"></i><b>1.5.1</b> Radius approach</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="burial-rites.html"><a href="burial-rites.html"><i class="fa fa-check"></i><b>2</b> Burial rites</a>
<ul>
<li class="chapter" data-level="2.1" data-path="burial-rites.html"><a href="burial-rites.html#data"><i class="fa fa-check"></i><b>2.1</b> Data</a></li>
<li class="chapter" data-level="2.2" data-path="burial-rites.html"><a href="burial-rites.html#multiple-correspondence-analysis"><i class="fa fa-check"></i><b>2.2</b> Multiple correspondence analysis</a></li>
<li class="chapter" data-level="2.3" data-path="burial-rites.html"><a href="burial-rites.html#upset-plot"><i class="fa fa-check"></i><b>2.3</b> UpSet plot</a></li>
<li class="chapter" data-level="2.4" data-path="burial-rites.html"><a href="burial-rites.html#mca-biplots"><i class="fa fa-check"></i><b>2.4</b> MCA Biplots</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="burial-rites.html"><a href="burial-rites.html#biplot"><i class="fa fa-check"></i><b>2.4.1</b> Biplot</a></li>
<li class="chapter" data-level="2.4.2" data-path="burial-rites.html"><a href="burial-rites.html#country"><i class="fa fa-check"></i><b>2.4.2</b> Country</a></li>
<li class="chapter" data-level="2.4.3" data-path="burial-rites.html"><a href="burial-rites.html#period"><i class="fa fa-check"></i><b>2.4.3</b> Period</a></li>
<li class="chapter" data-level="2.4.4" data-path="burial-rites.html"><a href="burial-rites.html#culture"><i class="fa fa-check"></i><b>2.4.4</b> Culture</a></li>
<li class="chapter" data-level="2.4.5" data-path="burial-rites.html"><a href="burial-rites.html#sex"><i class="fa fa-check"></i><b>2.4.5</b> Sex</a></li>
<li class="chapter" data-level="2.4.6" data-path="burial-rites.html"><a href="burial-rites.html#ancestry"><i class="fa fa-check"></i><b>2.4.6</b> Ancestry</a></li>
<li class="chapter" data-level="2.4.7" data-path="burial-rites.html"><a href="burial-rites.html#mobility"><i class="fa fa-check"></i><b>2.4.7</b> Mobility</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="burial-rites.html"><a href="burial-rites.html#modelling"><i class="fa fa-check"></i><b>2.5</b> Modelling</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="burial-orientation.html"><a href="burial-orientation.html"><i class="fa fa-check"></i><b>3</b> Burial orientation</a>
<ul>
<li class="chapter" data-level="3.1" data-path="burial-orientation.html"><a href="burial-orientation.html#data-1"><i class="fa fa-check"></i><b>3.1</b> Data</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="burial-orientation.html"><a href="burial-orientation.html#calculating-the-average"><i class="fa fa-check"></i><b>3.1.1</b> Calculating the average</a></li>
<li class="chapter" data-level="3.1.2" data-path="burial-orientation.html"><a href="burial-orientation.html#histograms-1"><i class="fa fa-check"></i><b>3.1.2</b> Histograms</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="burial-orientation.html"><a href="burial-orientation.html#exploration-and-visualization"><i class="fa fa-check"></i><b>3.2</b> Exploration and visualization</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="burial-orientation.html"><a href="burial-orientation.html#all-individuals"><i class="fa fa-check"></i><b>3.2.1</b> All individuals</a></li>
<li class="chapter" data-level="3.2.2" data-path="burial-orientation.html"><a href="burial-orientation.html#burial-side"><i class="fa fa-check"></i><b>3.2.2</b> Burial side</a></li>
<li class="chapter" data-level="3.2.3" data-path="burial-orientation.html"><a href="burial-orientation.html#country-1"><i class="fa fa-check"></i><b>3.2.3</b> Country</a></li>
<li class="chapter" data-level="3.2.4" data-path="burial-orientation.html"><a href="burial-orientation.html#period-1"><i class="fa fa-check"></i><b>3.2.4</b> Period</a></li>
<li class="chapter" data-level="3.2.5" data-path="burial-orientation.html"><a href="burial-orientation.html#culture-1"><i class="fa fa-check"></i><b>3.2.5</b> Culture</a></li>
<li class="chapter" data-level="3.2.6" data-path="burial-orientation.html"><a href="burial-orientation.html#sex-1"><i class="fa fa-check"></i><b>3.2.6</b> Sex</a></li>
<li class="chapter" data-level="3.2.7" data-path="burial-orientation.html"><a href="burial-orientation.html#age"><i class="fa fa-check"></i><b>3.2.7</b> Age</a></li>
<li class="chapter" data-level="3.2.8" data-path="burial-orientation.html"><a href="burial-orientation.html#ancestry-1"><i class="fa fa-check"></i><b>3.2.8</b> Ancestry</a></li>
<li class="chapter" data-level="3.2.9" data-path="burial-orientation.html"><a href="burial-orientation.html#mobility-1"><i class="fa fa-check"></i><b>3.2.9</b> Mobility</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="circular-statistics.html"><a href="circular-statistics.html"><i class="fa fa-check"></i><b>4</b> Circular statistics</a>
<ul>
<li class="chapter" data-level="4.1" data-path="circular-statistics.html"><a href="circular-statistics.html#test-circular-statistics-with-burial-sides"><i class="fa fa-check"></i><b>4.1</b> Test: circular statistics with burial sides</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="circular-statistics.html"><a href="circular-statistics.html#mean-and-variance"><i class="fa fa-check"></i><b>4.1.1</b> Mean and variance</a></li>
<li class="chapter" data-level="4.1.2" data-path="circular-statistics.html"><a href="circular-statistics.html#angular-distance"><i class="fa fa-check"></i><b>4.1.2</b> Angular distance</a></li>
<li class="chapter" data-level="4.1.3" data-path="circular-statistics.html"><a href="circular-statistics.html#visualization"><i class="fa fa-check"></i><b>4.1.3</b> Visualization</a></li>
<li class="chapter" data-level="4.1.4" data-path="circular-statistics.html"><a href="circular-statistics.html#p-value"><i class="fa fa-check"></i><b>4.1.4</b> P-value</a></li>
<li class="chapter" data-level="4.1.5" data-path="circular-statistics.html"><a href="circular-statistics.html#similarity"><i class="fa fa-check"></i><b>4.1.5</b> Similarity</a></li>
<li class="chapter" data-level="4.1.6" data-path="circular-statistics.html"><a href="circular-statistics.html#watson-william-test-and-circular-anova"><i class="fa fa-check"></i><b>4.1.6</b> Watson-William test and circular ANOVA</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="circular-statistics.html"><a href="circular-statistics.html#country-2"><i class="fa fa-check"></i><b>4.2</b> Country</a></li>
<li class="chapter" data-level="4.3" data-path="circular-statistics.html"><a href="circular-statistics.html#period-2"><i class="fa fa-check"></i><b>4.3</b> Period</a></li>
<li class="chapter" data-level="4.4" data-path="circular-statistics.html"><a href="circular-statistics.html#culture-2"><i class="fa fa-check"></i><b>4.4</b> Culture</a></li>
<li class="chapter" data-level="4.5" data-path="circular-statistics.html"><a href="circular-statistics.html#sex-2"><i class="fa fa-check"></i><b>4.5</b> Sex</a></li>
<li class="chapter" data-level="4.6" data-path="circular-statistics.html"><a href="circular-statistics.html#circular-linear-regression-models"><i class="fa fa-check"></i><b>4.6</b> Circular linear regression models</a>
<ul>
<li class="chapter" data-level="4.6.1" data-path="circular-statistics.html"><a href="circular-statistics.html#chg-1"><i class="fa fa-check"></i><b>4.6.1</b> CHG</a></li>
<li class="chapter" data-level="4.6.2" data-path="circular-statistics.html"><a href="circular-statistics.html#whg-1"><i class="fa fa-check"></i><b>4.6.2</b> WHG</a></li>
<li class="chapter" data-level="4.6.3" data-path="circular-statistics.html"><a href="circular-statistics.html#ehg-1"><i class="fa fa-check"></i><b>4.6.3</b> EHG</a></li>
<li class="chapter" data-level="4.6.4" data-path="circular-statistics.html"><a href="circular-statistics.html#lvn-1"><i class="fa fa-check"></i><b>4.6.4</b> LVN</a></li>
<li class="chapter" data-level="4.6.5" data-path="circular-statistics.html"><a href="circular-statistics.html#mobility-2"><i class="fa fa-check"></i><b>4.6.5</b> Mobility</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Cultural hitchhiking: burial rites and genomic variation in space and time</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="burial-data" class="section level1 hasAnchor" number="1">
<h1><span class="header-section-number">Chapter 1</span> Burial data<a href="burial-data.html#burial-data" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Here we are going to track the analysis on the data that Robert and Stephen shared with us.</p>
<p>We want to explore whether we can find a relationship between large scale human migrations and changes in burial practices during he Holocene.</p>
<p>We will analyse burial practices data against a Gaussian spatial process and values of human ancestry and mobility. The data we have are records of different burial types at grave sites across Europe.</p>
<p>Let’s first input the data. We are going to transform characters to factors for the explanatory variables we need, so we can check how many levels they have.</p>
<div id="data-table" class="section level2 hasAnchor" number="1.1">
<h2><span class="header-section-number">1.1</span> Data table<a href="burial-data.html#data-table" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="burial-data.html#cb1-1" tabindex="-1"></a><span class="co"># graves &lt;- fread(&quot;./EAA2024_burial_rite_data.csv&quot;, stringsAsFactors = F, na.strings = &quot;\\N&quot;)</span></span>
<span id="cb1-2"><a href="burial-data.html#cb1-2" tabindex="-1"></a>graves <span class="ot">&lt;-</span> <span class="fu">fread</span>(<span class="st">&quot;./Data/Burial.csv&quot;</span>, <span class="at">na.strings =</span> <span class="st">&quot;&quot;</span>)</span>
<span id="cb1-3"><a href="burial-data.html#cb1-3" tabindex="-1"></a>graves<span class="sc">$</span>DepositionType <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(graves<span class="sc">$</span>DepositionType)</span>
<span id="cb1-4"><a href="burial-data.html#cb1-4" tabindex="-1"></a>graves<span class="sc">$</span>BodyPositioning <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(graves<span class="sc">$</span>BodyPositioning)</span>
<span id="cb1-5"><a href="burial-data.html#cb1-5" tabindex="-1"></a>graves<span class="sc">$</span>BurialSide <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(graves<span class="sc">$</span>BurialSide)</span>
<span id="cb1-6"><a href="burial-data.html#cb1-6" tabindex="-1"></a><span class="fu">str</span>(graves)</span></code></pre></div>
<pre><code>## Classes &#39;data.table&#39; and &#39;data.frame&#39;:   4275 obs. of  83 variables:
##  $ IndividualID                         : chr  &quot;C00001&quot; &quot;C00002&quot; &quot;C00003&quot; &quot;C00004&quot; ...
##  $ aDNAID                               : chr  &quot;I16239&quot; &quot;I18091&quot; &quot;I17344&quot; NA ...
##  $ SiteID                               : chr  &quot;S10567&quot; &quot;S10567&quot; &quot;S10567&quot; &quot;S10567&quot; ...
##  $ Latitude                             : num  48.3 48.3 48.3 48.3 48.3 ...
##  $ Longitude                            : num  18.1 18.1 18.1 18.1 18.1 ...
##  $ PhaseID                              : chr  &quot;NITRHK1&quot; &quot;NITRHK1&quot; &quot;NITRHK1&quot; &quot;NITRHK1&quot; ...
##  $ gaussianModelMu                      : int  7052 7052 7052 7052 7052 7052 7052 7052 7052 7052 ...
##  $ gaussianModelSigma                   : int  102 102 102 102 102 102 102 102 102 102 ...
##  $ aDNACitationID                       : chr  &quot;gelab2023a&quot; &quot;gelab2023a&quot; &quot;gelab2023a&quot; NA ...
##  $ Sex                                  : num  1 0 0.25 0 0.5 1 0 0 0 0.5 ...
##  $ DepositionType                       : Factor w/ 6 levels &quot;bog body&quot;,&quot;cenotaph&quot;,..: 5 5 5 5 5 5 5 5 5 2 ...
##  $ RiteID                               : chr  &quot;R00001&quot; &quot;R00002&quot; &quot;R00003&quot; &quot;R00004&quot; ...
##  $ Dismembered                          : int  0 0 0 0 0 0 NA 0 0 NA ...
##  $ Head                                 : int  1 1 1 1 1 1 NA 1 1 NA ...
##  $ BodyPositioning                      : Factor w/ 9 levels &quot;crouched&quot;,&quot;extended&quot;,..: 1 1 1 1 1 1 NA 1 1 NA ...
##  $ BurialSide                           : Factor w/ 13 levels &quot;back&quot;,&quot;back/left&quot;,..: 8 10 8 8 8 10 NA 9 9 NA ...
##  $ BurialOrientationMin                 : int  180 126 106 178 140 166 90 119 130 135 ...
##  $ BurialOrientationMax                 : int  NA NA NA NA NA NA 180 NA NA 180 ...
##  $ GraveGoods                           : int  NA NA NA NA NA NA NA NA 0 NA ...
##  $ Ochre                                : int  0 0 0 0 0 0 1 0 0 0 ...
##  $ CitationID                           : chr  &quot;pavúk1972a&quot; &quot;pavúk1972a&quot; &quot;pavúk1972a&quot; &quot;pavúk1972a&quot; ...
##  $ time_added                           : POSIXct, format: &quot;2024-04-25 02:08:01&quot; &quot;2024-04-25 02:08:01&quot; ...
##  $ user_added                           : chr  &quot;robert@localhost&quot; &quot;robert@localhost&quot; &quot;robert@localhost&quot; &quot;robert@localhost&quot; ...
##  $ time_last_update                     : POSIXct, format: &quot;2024-04-26 04:59:08&quot; &quot;2024-04-26 04:59:08&quot; ...
##  $ user_last_update                     : chr  &quot;Rscripts@localhost&quot; &quot;Rscripts@localhost&quot; &quot;Rscripts@localhost&quot; &quot;Rscripts@localhost&quot; ...
##  $ DepositionType_bog body              : int  0 0 0 0 0 0 0 0 0 0 ...
##  $ DepositionType_cenotaph              : int  0 0 0 0 0 0 0 0 0 1 ...
##  $ DepositionType_cremation             : int  0 0 0 0 0 0 0 0 0 0 ...
##  $ DepositionType_disarticulated        : int  0 0 0 0 0 0 0 0 0 0 ...
##  $ DepositionType_inhumation            : int  1 1 1 1 1 1 1 1 1 0 ...
##  $ DepositionType_inhumation: carbonized: int  0 0 0 0 0 0 0 0 0 0 ...
##  $ BodyPositioning_crouched             : int  1 1 1 1 1 1 NA 1 1 NA ...
##  $ BodyPositioning_extended             : int  0 0 0 0 0 0 NA 0 0 NA ...
##  $ BodyPositioning_extended, rhomboid   : int  0 0 0 0 0 0 NA 0 0 NA ...
##  $ BodyPositioning_heap                 : int  0 0 0 0 0 0 NA 0 0 NA ...
##  $ BodyPositioning_inside a vessel      : int  0 0 0 0 0 0 NA 0 0 NA ...
##  $ BodyPositioning_irregular            : int  0 0 0 0 0 0 NA 0 0 NA ...
##  $ BodyPositioning_prone                : int  0 0 0 0 0 0 NA 0 0 NA ...
##  $ BodyPositioning_scattered            : int  0 0 0 0 0 0 NA 0 0 NA ...
##  $ BodyPositioning_sitting              : int  0 0 0 0 0 0 NA 0 0 NA ...
##  $ BurialSide_back                      : int  0 0 0 0 0 0 NA 0 0 NA ...
##  $ BurialSide_back/left                 : int  0 0 0 0 0 0 NA 0 0 NA ...
##  $ BurialSide_back/right                : int  0 0 0 0 0 0 NA 0 0 NA ...
##  $ BurialSide_bottom                    : int  0 0 0 0 0 0 NA 0 0 NA ...
##  $ BurialSide_front                     : int  0 0 0 0 0 0 NA 0 0 NA ...
##  $ BurialSide_front/left                : int  0 0 0 0 0 0 NA 0 0 NA ...
##  $ BurialSide_front/right               : int  0 0 0 0 0 0 NA 0 0 NA ...
##  $ BurialSide_left                      : int  1 0 1 1 1 0 NA 0 0 NA ...
##  $ BurialSide_left/back                 : int  0 0 0 0 0 0 NA 1 1 NA ...
##  $ BurialSide_left/front                : int  0 1 0 0 0 1 NA 0 0 NA ...
##  $ BurialSide_right                     : int  0 0 0 0 0 0 NA 0 0 NA ...
##  $ BurialSide_right/back                : int  0 0 0 0 0 0 NA 0 0 NA ...
##  $ BurialSide_right/front               : int  0 0 0 0 0 0 NA 0 0 NA ...
##  $ Num                                  : int  3096 3143 3132 1 3133 3144 3134 3148 3101 2 ...
##  $ TIME                                 : num  NA NA NA NA NA NA NA NA NA NA ...
##  $ ANCE1                                : num  0.000132 0.000132 0.000132 0.000132 0.000132 0.000132 0.000132 0.000132 0.000132 0.000132 ...
##  $ ANCE2                                : num  1e-05 1e-05 1e-05 1e-05 1e-05 1e-05 1e-05 1e-05 1e-05 1e-05 ...
##  $ ANCE3                                : num  0.00118 0.00118 0.00118 0.00118 0.00118 ...
##  $ ANCE4                                : num  0.0541 0.0541 0.0541 0.0541 0.0541 ...
##  $ ANCE5                                : num  0.00933 0.00933 0.00933 0.00933 0.00933 ...
##  $ ANCE6                                : num  0.897 0.897 0.897 0.897 0.897 ...
##  $ ANCE7                                : num  1e-05 1e-05 1e-05 1e-05 1e-05 1e-05 1e-05 1e-05 1e-05 1e-05 ...
##  $ ANCE8                                : num  0.0386 0.0386 0.0386 0.0386 0.0386 ...
##  $ ANCE9                                : num  2.4e-05 2.4e-05 2.4e-05 2.4e-05 2.4e-05 2.4e-05 2.4e-05 2.4e-05 2.4e-05 2.4e-05 ...
##  $ ov_dist_mds2_retro_default           : int  390 390 390 390 390 390 390 390 390 390 ...
##  $ ov_dist_pca5_retro_default           : int  368 368 368 368 368 368 368 368 368 368 ...
##  $ Date_BP_Median                       : int  NA NA NA NA NA NA NA NA NA NA ...
##  $ YearBP                               : int  7052 7052 7052 7052 7052 7052 7052 7052 7052 7052 ...
##  $ MobilityMatch_distance               : num  91.8 91.8 91.8 91.8 91.8 ...
##  $ mobility_MDS_method2                 : num  410 410 410 410 410 ...
##  $ mobility_PCA_method2                 : num  604 604 604 604 604 ...
##  $ AncestryMatch_distance               : num  182 182 182 182 182 ...
##  $ ANCE1_v2                             : num  0.000545 0.000545 0.000545 0.000545 0.000545 ...
##  $ ANCE2_v2                             : num  0.0148 0.0148 0.0148 0.0148 0.0148 ...
##  $ ANCE3_v2                             : num  0.00252 0.00252 0.00252 0.00252 0.00252 ...
##  $ ANCE4_v2                             : num  0.097 0.097 0.097 0.097 0.097 ...
##  $ ANCE5_v2                             : num  0.00479 0.00479 0.00479 0.00479 0.00479 ...
##  $ ANCE6_v2                             : num  0.829 0.829 0.829 0.829 0.829 ...
##  $ ANCE7_v2                             : num  1e-05 1e-05 1e-05 1e-05 1e-05 1e-05 1e-05 1e-05 1e-05 1e-05 ...
##  $ ANCE8_v2                             : num  0.048 0.048 0.048 0.048 0.048 ...
##  $ ANCE9_v2                             : num  0.00287 0.00287 0.00287 0.00287 0.00287 ...
##  $ mobility_MDS_250y_retrospective      : num  156 156 156 156 156 ...
##  $ mobility_PCA_250y_retrospective      : num  361 361 361 361 361 ...
##  - attr(*, &quot;.internal.selfref&quot;)=&lt;externalptr&gt;</code></pre>
<p>As we can see, some of the variables we are most interested in, such as the positioning of the body and the burial side, have more than 2 levels. This means that there are more than 2 descriptors for each variable. This makes it tricky because we cannot model factors with more that 2 levels. Therefore, we will create new columns in the database where we transform the factors to a binomial presence/absence data (0/1).</p>
<p>Also, for the Burial Side variable, we have a level called “left?” in the original data table, what should we do with this? Can we group this with the left or not? For now I grouped it because it consists of just 5 records, but we can decide later whether we should keep it separate or not.</p>
<p>Let’s plot the data to see what we are working with.</p>
</div>
<div id="histograms" class="section level2 hasAnchor" number="1.2">
<h2><span class="header-section-number">1.2</span> Histograms<a href="burial-data.html#histograms" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><img src="_main_files/figure-html/unnamed-chunk-5-1.png" width="672" /><img src="_main_files/figure-html/unnamed-chunk-5-2.png" width="672" /><img src="_main_files/figure-html/unnamed-chunk-5-3.png" width="672" /><img src="_main_files/figure-html/unnamed-chunk-5-4.png" width="672" /><img src="_main_files/figure-html/unnamed-chunk-5-5.png" width="672" /><img src="_main_files/figure-html/unnamed-chunk-5-6.png" width="672" /><img src="_main_files/figure-html/unnamed-chunk-5-7.png" width="672" /><img src="_main_files/figure-html/unnamed-chunk-5-8.png" width="672" /></p>
<p>The burial orientation seems interesting because the majority of the data lies on specific angles, for example: 0, 45, 90, 135, 180, 225, and 270.</p>
<p>The body positioning also seems to aggregate towards “crouched”, “inside a vessel”, “extended”, and “scattered”, with the two most represented groups being “crouched” and “inside a vessel”.</p>
<p>Now let’s check the proportion of NA, zeros and ones, after we transformed factors to binary:</p>
<p><img src="_main_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
</div>
<div id="temporal-patterns" class="section level2 hasAnchor" number="1.3">
<h2><span class="header-section-number">1.3</span> Temporal patterns<a href="burial-data.html#temporal-patterns" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Do we see any temporal patterns?</p>
<p><img src="_main_files/figure-html/unnamed-chunk-7-1.png" width="672" /><img src="_main_files/figure-html/unnamed-chunk-7-2.png" width="672" /><img src="_main_files/figure-html/unnamed-chunk-7-3.png" width="672" /><img src="_main_files/figure-html/unnamed-chunk-7-4.png" width="672" /><img src="_main_files/figure-html/unnamed-chunk-7-5.png" width="672" /><img src="_main_files/figure-html/unnamed-chunk-7-6.png" width="672" /><img src="_main_files/figure-html/unnamed-chunk-7-7.png" width="672" /><img src="_main_files/figure-html/unnamed-chunk-7-8.png" width="672" /></p>
</div>
<div id="spatiotemporal-patterns" class="section level2 hasAnchor" number="1.4">
<h2><span class="header-section-number">1.4</span> Spatiotemporal patterns<a href="burial-data.html#spatiotemporal-patterns" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Now let’s plot everything is space and time:</p>
<p><img src="_main_files/figure-html/unnamed-chunk-8-1.png" width="672" /><img src="_main_files/figure-html/unnamed-chunk-8-2.png" width="672" /><img src="_main_files/figure-html/unnamed-chunk-8-3.png" width="672" /><img src="_main_files/figure-html/unnamed-chunk-8-4.png" width="672" /><img src="_main_files/figure-html/unnamed-chunk-8-5.png" width="672" /><img src="_main_files/figure-html/unnamed-chunk-8-6.png" width="672" /></p>
<p>Both in space and time we do not see a clear pattern, except maybe for the Burial Side variable over time. We will still build a mesh and a Gaussian spatial process for the sites, which will be used as an explanatory variable in the model.</p>
</div>
<div id="adding-ancestry-and-mobility" class="section level2 hasAnchor" number="1.5">
<h2><span class="header-section-number">1.5</span> Adding ancestry and mobility<a href="burial-data.html#adding-ancestry-and-mobility" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The next step is to pair the grave individuals with human ancestry and mobility data. For some of them, the aDNAID will match, so we have confidence that the values assigned to those graves are correct. For others, we might have to take values of ancestry and mobility of the closest individuals in space and time.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="burial-data.html#cb3-1" tabindex="-1"></a><span class="do">## Ancestry</span></span>
<span id="cb3-2"><a href="burial-data.html#cb3-2" tabindex="-1"></a>ancestry <span class="ot">&lt;-</span> <span class="fu">fread</span>(<span class="st">&quot;../MesoNeo/MesoNeo/Data3/combined.tsv&quot;</span>)</span>
<span id="cb3-3"><a href="burial-data.html#cb3-3" tabindex="-1"></a>info <span class="ot">&lt;-</span> <span class="fu">fread</span>(<span class="st">&quot;/Users/msb290/Library/CloudStorage/OneDrive-UniversityofCopenhagen/MesoNeo/MesoNeo/Data3/neo.impute.1000g.sampleInfo_clusterInfo.txt&quot;</span>)</span>
<span id="cb3-4"><a href="burial-data.html#cb3-4" tabindex="-1"></a>ancestry2 <span class="ot">&lt;-</span> <span class="fu">melt</span>(ancestry, <span class="at">id.vars =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>, <span class="at">measure.vars =</span> <span class="dv">5</span><span class="sc">:</span><span class="dv">13</span>, <span class="at">variable.name =</span> <span class="st">&quot;ANCE&quot;</span>)</span>
<span id="cb3-5"><a href="burial-data.html#cb3-5" tabindex="-1"></a>ancestry2 <span class="ot">&lt;-</span> <span class="fu">merge</span>(ancestry2, info[, .(sampleId, country, region, groupLabel, clusterAlias)], <span class="at">by.x =</span> <span class="st">&quot;IND&quot;</span>, <span class="at">by.y =</span> <span class="st">&quot;sampleId&quot;</span>)</span>
<span id="cb3-6"><a href="burial-data.html#cb3-6" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> ancestry2, <span class="fu">aes</span>(<span class="at">x =</span> forcats<span class="sc">::</span><span class="fu">fct_reorder</span>(IND, TIME, <span class="at">.desc =</span> T), <span class="at">y =</span> value, <span class="at">color =</span> ANCE, <span class="at">fill =</span> ANCE)) <span class="sc">+</span></span>
<span id="cb3-7"><a href="burial-data.html#cb3-7" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">&#39;identity&#39;</span>) <span class="sc">+</span> </span>
<span id="cb3-8"><a href="burial-data.html#cb3-8" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> pals<span class="sc">::</span><span class="fu">coolwarm</span>(<span class="dv">9</span>)) <span class="sc">+</span> </span>
<span id="cb3-9"><a href="burial-data.html#cb3-9" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> pals<span class="sc">::</span><span class="fu">coolwarm</span>(<span class="dv">9</span>)) <span class="sc">+</span> </span>
<span id="cb3-10"><a href="burial-data.html#cb3-10" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>region, <span class="at">scales =</span> <span class="st">&quot;free&quot;</span>) <span class="sc">+</span> </span>
<span id="cb3-11"><a href="burial-data.html#cb3-11" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span> </span>
<span id="cb3-12"><a href="burial-data.html#cb3-12" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_blank</span>(), </span>
<span id="cb3-13"><a href="burial-data.html#cb3-13" tabindex="-1"></a>        <span class="at">axis.ticks.x =</span> <span class="fu">element_blank</span>(), </span>
<span id="cb3-14"><a href="burial-data.html#cb3-14" tabindex="-1"></a>        <span class="at">panel.grid =</span> <span class="fu">element_blank</span>())</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="burial-data.html#cb4-1" tabindex="-1"></a><span class="do">## Mobility</span></span>
<span id="cb4-2"><a href="burial-data.html#cb4-2" tabindex="-1"></a>ov <span class="ot">&lt;-</span> <span class="fu">fread</span>(<span class="st">&quot;~/Documents/Postdoc/mobest/tables/Dataset_S3.csv&quot;</span>)</span>
<span id="cb4-3"><a href="burial-data.html#cb4-3" tabindex="-1"></a>ov2 <span class="ot">&lt;-</span> <span class="fu">fread</span>(<span class="st">&quot;~/Library/CloudStorage/OneDrive-UniversityofCopenhagen/mobest/tables/mobility_estimates_250y_retrospecive_distance.csv&quot;</span>)</span>
<span id="cb4-4"><a href="burial-data.html#cb4-4" tabindex="-1"></a>info <span class="ot">&lt;-</span> <span class="fu">fread</span>(<span class="st">&quot;~/Documents/Postdoc/mobest/tables/Dataset_S1.csv&quot;</span>)</span>
<span id="cb4-5"><a href="burial-data.html#cb4-5" tabindex="-1"></a>mobility <span class="ot">&lt;-</span> <span class="fu">merge</span>(ov2, info, <span class="at">by =</span> <span class="st">&quot;Sample_ID&quot;</span>, <span class="at">all.x =</span> T)</span>
<span id="cb4-6"><a href="burial-data.html#cb4-6" tabindex="-1"></a><span class="fu">rm</span>(ov, ov2, info)</span>
<span id="cb4-7"><a href="burial-data.html#cb4-7" tabindex="-1"></a><span class="co"># remove modern individuals</span></span>
<span id="cb4-8"><a href="burial-data.html#cb4-8" tabindex="-1"></a>ancestry <span class="ot">&lt;-</span> ancestry[TIME <span class="sc">&gt;</span> <span class="dv">0</span>]</span>
<span id="cb4-9"><a href="burial-data.html#cb4-9" tabindex="-1"></a><span class="co"># transform time of mobility data from BC/AD to cal BP</span></span>
<span id="cb4-10"><a href="burial-data.html#cb4-10" tabindex="-1"></a>mobility[, Date_BP_Start <span class="sc">:=</span> <span class="dv">1950</span> <span class="sc">-</span> Date_BC_AD_Start]</span>
<span id="cb4-11"><a href="burial-data.html#cb4-11" tabindex="-1"></a>mobility[, Date_BP_Median <span class="sc">:=</span> <span class="dv">1950</span> <span class="sc">-</span> Date_BC_AD_Median]</span>
<span id="cb4-12"><a href="burial-data.html#cb4-12" tabindex="-1"></a>mobility[, Date_BP_Stop <span class="sc">:=</span> <span class="dv">1950</span> <span class="sc">-</span> Date_BC_AD_Stop]</span>
<span id="cb4-13"><a href="burial-data.html#cb4-13" tabindex="-1"></a></span>
<span id="cb4-14"><a href="burial-data.html#cb4-14" tabindex="-1"></a><span class="co"># Number of common IDs</span></span>
<span id="cb4-15"><a href="burial-data.html#cb4-15" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">which</span>(graves<span class="sc">$</span>aDNAID <span class="sc">%in%</span> ancestry<span class="sc">$</span>IND)) <span class="co"># 3%</span></span></code></pre></div>
<pre><code>## [1] 144</code></pre>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="burial-data.html#cb6-1" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">which</span>(graves<span class="sc">$</span>aDNAID <span class="sc">%in%</span> mobility<span class="sc">$</span>Sample_ID)) <span class="co"># 11%</span></span></code></pre></div>
<pre><code>## [1] 462</code></pre>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="burial-data.html#cb8-1" tabindex="-1"></a><span class="co"># Merge together</span></span>
<span id="cb8-2"><a href="burial-data.html#cb8-2" tabindex="-1"></a>graves <span class="ot">&lt;-</span> <span class="fu">merge</span>(graves, ancestry[, .(IND, TIME, ANCE1, ANCE2, ANCE3, ANCE4, ANCE5, ANCE6, ANCE7, ANCE8, ANCE9)], <span class="at">by.x =</span> <span class="st">&quot;aDNAID&quot;</span>, <span class="at">by.y =</span> <span class="st">&quot;IND&quot;</span>, <span class="at">all.x =</span> T)</span>
<span id="cb8-3"><a href="burial-data.html#cb8-3" tabindex="-1"></a>graves <span class="ot">&lt;-</span> <span class="fu">merge</span>(graves, mobility[, .(Sample_ID, ov_dist_mds2_retro_default, ov_dist_pca5_retro_default, Date_BP_Median)], <span class="at">by.x =</span> <span class="st">&quot;aDNAID&quot;</span>, <span class="at">by.y =</span> <span class="st">&quot;Sample_ID&quot;</span>, <span class="at">all.x =</span> T)</span>
<span id="cb8-4"><a href="burial-data.html#cb8-4" tabindex="-1"></a></span>
<span id="cb8-5"><a href="burial-data.html#cb8-5" tabindex="-1"></a><span class="co"># Reconcile ages BP</span></span>
<span id="cb8-6"><a href="burial-data.html#cb8-6" tabindex="-1"></a>graves[, YearBP <span class="sc">:=</span> gaussianModelMu]</span>
<span id="cb8-7"><a href="burial-data.html#cb8-7" tabindex="-1"></a>graves[<span class="sc">!</span><span class="fu">is.na</span>(TIME)]<span class="sc">$</span>YearBP <span class="ot">&lt;-</span> graves[<span class="sc">!</span><span class="fu">is.na</span>(TIME)]<span class="sc">$</span>TIME</span>
<span id="cb8-8"><a href="burial-data.html#cb8-8" tabindex="-1"></a>graves[<span class="sc">!</span><span class="fu">is.na</span>(Date_BP_Median)]<span class="sc">$</span>YearBP <span class="ot">&lt;-</span> graves[<span class="sc">!</span><span class="fu">is.na</span>(Date_BP_Median)]<span class="sc">$</span>Date_BP_Median</span></code></pre></div>
<p>We have matched the common IDs, now we try and find the closest individuals to assign the values, starting with mobility estimates.</p>
<p>To match the sites, we will calculate the distances between individuals both in space and in time. We will then add the distances together to calculate values of distances in time and space. We will then extract the individuals with the minimum spatiotemporal distance. We have one problem: for 279 graves we do not have an age and therefore we cannot calculate a spatiotemporal distance. I would be cautious of assigning values of mobility and ancestry only based on spatial distance, so I will remove them.</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="burial-data.html#cb9-1" tabindex="-1"></a>graves[, Num <span class="sc">:=</span> <span class="dv">1</span><span class="sc">:</span>.N]</span>
<span id="cb9-2"><a href="burial-data.html#cb9-2" tabindex="-1"></a></span>
<span id="cb9-3"><a href="burial-data.html#cb9-3" tabindex="-1"></a><span class="co"># Subset data to individuals with no estimates of mobility</span></span>
<span id="cb9-4"><a href="burial-data.html#cb9-4" tabindex="-1"></a>miss <span class="ot">&lt;-</span> graves[<span class="fu">is.na</span>(ov_dist_mds2_retro_default)]</span>
<span id="cb9-5"><a href="burial-data.html#cb9-5" tabindex="-1"></a></span>
<span id="cb9-6"><a href="burial-data.html#cb9-6" tabindex="-1"></a><span class="co"># Remove individuals for which we do not have an age</span></span>
<span id="cb9-7"><a href="burial-data.html#cb9-7" tabindex="-1"></a>miss <span class="ot">&lt;-</span> miss[<span class="sc">!</span><span class="fu">is.na</span>(YearBP)]</span>
<span id="cb9-8"><a href="burial-data.html#cb9-8" tabindex="-1"></a></span>
<span id="cb9-9"><a href="burial-data.html#cb9-9" tabindex="-1"></a><span class="co"># Transform to points under equal-area projection</span></span>
<span id="cb9-10"><a href="burial-data.html#cb9-10" tabindex="-1"></a>gr_pnts <span class="ot">&lt;-</span> <span class="fu">project</span>(</span>
<span id="cb9-11"><a href="burial-data.html#cb9-11" tabindex="-1"></a>    <span class="fu">vect</span>(<span class="at">x =</span> miss[, .(Longitude, Latitude, ov_dist_mds2_retro_default, aDNAID)],</span>
<span id="cb9-12"><a href="burial-data.html#cb9-12" tabindex="-1"></a>                 <span class="at">geom =</span> <span class="fu">c</span>(<span class="st">&quot;Longitude&quot;</span>, <span class="st">&quot;Latitude&quot;</span>), <span class="at">crs =</span> <span class="fu">crs</span>(<span class="fu">rast</span>())), </span>
<span id="cb9-13"><a href="burial-data.html#cb9-13" tabindex="-1"></a>    proj</span>
<span id="cb9-14"><a href="burial-data.html#cb9-14" tabindex="-1"></a>  )</span>
<span id="cb9-15"><a href="burial-data.html#cb9-15" tabindex="-1"></a>mob_pnts <span class="ot">&lt;-</span> <span class="fu">project</span>(</span>
<span id="cb9-16"><a href="burial-data.html#cb9-16" tabindex="-1"></a>  <span class="fu">vect</span>(mobility[, .(Longitude, Latitude, Sample_ID)], </span>
<span id="cb9-17"><a href="burial-data.html#cb9-17" tabindex="-1"></a>         <span class="at">geom =</span> <span class="fu">c</span>(<span class="st">&quot;Longitude&quot;</span>, <span class="st">&quot;Latitude&quot;</span>),</span>
<span id="cb9-18"><a href="burial-data.html#cb9-18" tabindex="-1"></a>         <span class="at">crs =</span> <span class="fu">crs</span>(<span class="fu">rast</span>())), </span>
<span id="cb9-19"><a href="burial-data.html#cb9-19" tabindex="-1"></a>  proj</span>
<span id="cb9-20"><a href="burial-data.html#cb9-20" tabindex="-1"></a>)</span></code></pre></div>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="burial-data.html#cb10-1" tabindex="-1"></a>conts_prj <span class="ot">&lt;-</span> <span class="fu">st_transform</span>(conts, <span class="at">crs =</span> proj)</span>
<span id="cb10-2"><a href="burial-data.html#cb10-2" tabindex="-1"></a>e <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">min</span>(<span class="fu">c</span>(<span class="fu">ext</span>(mob_pnts)[<span class="dv">1</span>], <span class="fu">ext</span>(gr_pnts)[<span class="dv">1</span>])),</span>
<span id="cb10-3"><a href="burial-data.html#cb10-3" tabindex="-1"></a>       <span class="fu">max</span>(<span class="fu">c</span>(<span class="fu">ext</span>(mob_pnts)[<span class="dv">2</span>], <span class="fu">ext</span>(gr_pnts)[<span class="dv">2</span>])),</span>
<span id="cb10-4"><a href="burial-data.html#cb10-4" tabindex="-1"></a>       <span class="fu">min</span>(<span class="fu">c</span>(<span class="fu">ext</span>(mob_pnts)[<span class="dv">3</span>], <span class="fu">ext</span>(gr_pnts)[<span class="dv">3</span>])),</span>
<span id="cb10-5"><a href="burial-data.html#cb10-5" tabindex="-1"></a>       <span class="fu">max</span>(<span class="fu">c</span>(<span class="fu">ext</span>(mob_pnts)[<span class="dv">4</span>], <span class="fu">ext</span>(gr_pnts)[<span class="dv">4</span>])))</span>
<span id="cb10-6"><a href="burial-data.html#cb10-6" tabindex="-1"></a><span class="fu">plot</span>(mob_pnts, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">xlim =</span> e[<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>], <span class="at">ylim =</span> e[<span class="dv">3</span><span class="sc">:</span><span class="dv">4</span>]); <span class="fu">points</span>(gr_pnts, <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>); <span class="fu">plot</span>(conts_prj<span class="sc">$</span>geometry, <span class="at">add =</span> T)</span></code></pre></div>
<p>Here we get the closest individual in spatiotemporal distance.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="burial-data.html#cb11-1" tabindex="-1"></a><span class="co"># Calculate euclidean distance in space</span></span>
<span id="cb11-2"><a href="burial-data.html#cb11-2" tabindex="-1"></a>spatdists <span class="ot">&lt;-</span> <span class="fu">distance</span>(gr_pnts, mob_pnts, <span class="at">unit =</span> <span class="st">&quot;km&quot;</span>)</span>
<span id="cb11-3"><a href="burial-data.html#cb11-3" tabindex="-1"></a></span>
<span id="cb11-4"><a href="burial-data.html#cb11-4" tabindex="-1"></a><span class="co"># Calculate euclidean distance in time</span></span>
<span id="cb11-5"><a href="burial-data.html#cb11-5" tabindex="-1"></a>pairs <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(miss<span class="sc">$</span>YearBP, mobility<span class="sc">$</span>Date_BP_Median)</span>
<span id="cb11-6"><a href="burial-data.html#cb11-6" tabindex="-1"></a>tempdists <span class="ot">&lt;-</span> <span class="fu">apply</span>(pairs, <span class="dv">1</span>, <span class="cf">function</span>(r) <span class="fu">sqrt</span>(<span class="fu">sum</span>((r[<span class="dv">1</span>] <span class="sc">-</span> r[<span class="dv">2</span>])<span class="sc">^</span><span class="dv">2</span>)))</span>
<span id="cb11-7"><a href="burial-data.html#cb11-7" tabindex="-1"></a>tempdists <span class="ot">&lt;-</span> <span class="fu">matrix</span>(tempdists, </span>
<span id="cb11-8"><a href="burial-data.html#cb11-8" tabindex="-1"></a>                    <span class="at">nrow =</span> <span class="fu">length</span>(miss<span class="sc">$</span>YearBP), </span>
<span id="cb11-9"><a href="burial-data.html#cb11-9" tabindex="-1"></a>                    <span class="at">ncol =</span> <span class="fu">length</span>(mobility<span class="sc">$</span>Date_BP_Median))</span>
<span id="cb11-10"><a href="burial-data.html#cb11-10" tabindex="-1"></a></span>
<span id="cb11-11"><a href="burial-data.html#cb11-11" tabindex="-1"></a><span class="co"># spatiotemporal distances (euclidean with km == year)</span></span>
<span id="cb11-12"><a href="burial-data.html#cb11-12" tabindex="-1"></a>st_dists <span class="ot">&lt;-</span> <span class="fu">sqrt</span>((spatdists <span class="sc">+</span> tempdists)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb11-13"><a href="burial-data.html#cb11-13" tabindex="-1"></a></span>
<span id="cb11-14"><a href="burial-data.html#cb11-14" tabindex="-1"></a><span class="co"># Find minimum spatial distance</span></span>
<span id="cb11-15"><a href="burial-data.html#cb11-15" tabindex="-1"></a>find_min <span class="ot">&lt;-</span> <span class="cf">function</span>(row) {</span>
<span id="cb11-16"><a href="burial-data.html#cb11-16" tabindex="-1"></a>  <span class="fu">which</span>(row <span class="sc">==</span> <span class="fu">min</span>(row))</span>
<span id="cb11-17"><a href="burial-data.html#cb11-17" tabindex="-1"></a>}</span>
<span id="cb11-18"><a href="burial-data.html#cb11-18" tabindex="-1"></a>min_columns <span class="ot">&lt;-</span> <span class="fu">apply</span>(st_dists, <span class="dv">1</span>, find_min)</span>
<span id="cb11-19"><a href="burial-data.html#cb11-19" tabindex="-1"></a>min_dists <span class="ot">&lt;-</span> <span class="fu">apply</span>(st_dists, <span class="dv">1</span>, min)</span>
<span id="cb11-20"><a href="burial-data.html#cb11-20" tabindex="-1"></a></span>
<span id="cb11-21"><a href="burial-data.html#cb11-21" tabindex="-1"></a><span class="co"># Get Sample_ID in mobility table</span></span>
<span id="cb11-22"><a href="burial-data.html#cb11-22" tabindex="-1"></a>ids <span class="ot">&lt;-</span> <span class="fu">lapply</span>(min_columns, <span class="cf">function</span>(x) mobility<span class="sc">$</span>Sample_ID[x])</span></code></pre></div>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="burial-data.html#cb12-1" tabindex="-1"></a>gr_pnts <span class="ot">&lt;-</span> <span class="fu">project</span>(</span>
<span id="cb12-2"><a href="burial-data.html#cb12-2" tabindex="-1"></a>  <span class="fu">vect</span>(graves[, .(Longitude, Latitude, aDNAID, Num)], <span class="at">geom =</span> <span class="fu">c</span>(<span class="st">&quot;Longitude&quot;</span>, <span class="st">&quot;Latitude&quot;</span>), </span>
<span id="cb12-3"><a href="burial-data.html#cb12-3" tabindex="-1"></a>                <span class="at">crs =</span> <span class="fu">crs</span>(<span class="fu">rast</span>())),</span>
<span id="cb12-4"><a href="burial-data.html#cb12-4" tabindex="-1"></a>  proj)</span>
<span id="cb12-5"><a href="burial-data.html#cb12-5" tabindex="-1"></a>ance_pnts <span class="ot">&lt;-</span> <span class="fu">project</span>(</span>
<span id="cb12-6"><a href="burial-data.html#cb12-6" tabindex="-1"></a>  <span class="fu">vect</span>(ancestry[, .(LON, LAT, IND)], </span>
<span id="cb12-7"><a href="burial-data.html#cb12-7" tabindex="-1"></a>                 <span class="at">geom =</span> <span class="fu">c</span>(<span class="st">&quot;LON&quot;</span>, <span class="st">&quot;LAT&quot;</span>),</span>
<span id="cb12-8"><a href="burial-data.html#cb12-8" tabindex="-1"></a>                 <span class="at">crs =</span> <span class="fu">crs</span>(<span class="fu">rast</span>())),</span>
<span id="cb12-9"><a href="burial-data.html#cb12-9" tabindex="-1"></a>  proj)</span>
<span id="cb12-10"><a href="burial-data.html#cb12-10" tabindex="-1"></a>mob_pnts <span class="ot">&lt;-</span> <span class="fu">project</span>(</span>
<span id="cb12-11"><a href="burial-data.html#cb12-11" tabindex="-1"></a>  <span class="fu">vect</span>(mobility[, .(Longitude, Latitude, Sample_ID)], </span>
<span id="cb12-12"><a href="burial-data.html#cb12-12" tabindex="-1"></a>                 <span class="at">geom =</span> <span class="fu">c</span>(<span class="st">&quot;Longitude&quot;</span>, <span class="st">&quot;Latitude&quot;</span>),</span>
<span id="cb12-13"><a href="burial-data.html#cb12-13" tabindex="-1"></a>                 <span class="at">crs =</span> <span class="fu">crs</span>(<span class="fu">rast</span>())),</span>
<span id="cb12-14"><a href="burial-data.html#cb12-14" tabindex="-1"></a>  proj)</span>
<span id="cb12-15"><a href="burial-data.html#cb12-15" tabindex="-1"></a></span>
<span id="cb12-16"><a href="burial-data.html#cb12-16" tabindex="-1"></a>e <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">min</span>(<span class="fu">c</span>(<span class="fu">ext</span>(mob_pnts)[<span class="dv">1</span>], <span class="fu">ext</span>(gr_pnts)[<span class="dv">1</span>]), <span class="fu">ext</span>(ance_pnts)[<span class="dv">1</span>]),</span>
<span id="cb12-17"><a href="burial-data.html#cb12-17" tabindex="-1"></a>       <span class="fu">max</span>(<span class="fu">c</span>(<span class="fu">ext</span>(mob_pnts)[<span class="dv">2</span>], <span class="fu">ext</span>(gr_pnts)[<span class="dv">2</span>]), <span class="fu">ext</span>(ance_pnts)[<span class="dv">2</span>]),</span>
<span id="cb12-18"><a href="burial-data.html#cb12-18" tabindex="-1"></a>       <span class="fu">min</span>(<span class="fu">c</span>(<span class="fu">ext</span>(mob_pnts)[<span class="dv">3</span>], <span class="fu">ext</span>(gr_pnts)[<span class="dv">3</span>]), <span class="fu">ext</span>(ance_pnts)[<span class="dv">3</span>]),</span>
<span id="cb12-19"><a href="burial-data.html#cb12-19" tabindex="-1"></a>       <span class="fu">max</span>(<span class="fu">c</span>(<span class="fu">ext</span>(mob_pnts)[<span class="dv">4</span>], <span class="fu">ext</span>(gr_pnts)[<span class="dv">4</span>]), <span class="fu">ext</span>(ance_pnts)[<span class="dv">4</span>]))</span>
<span id="cb12-20"><a href="burial-data.html#cb12-20" tabindex="-1"></a>conts_prj <span class="ot">&lt;-</span> <span class="fu">st_transform</span>(conts, <span class="at">crs =</span> proj)</span>
<span id="cb12-21"><a href="burial-data.html#cb12-21" tabindex="-1"></a><span class="fu">plot</span>(conts_prj<span class="sc">$</span>geometry, <span class="at">xlim =</span> e[<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>], <span class="at">ylim =</span> e[<span class="dv">3</span><span class="sc">:</span><span class="dv">4</span>]); <span class="fu">points</span>(ance_pnts, <span class="at">bg =</span> <span class="st">&quot;skyblue&quot;</span>, <span class="at">pch =</span> <span class="dv">21</span>, <span class="at">cex =</span> <span class="fl">1.5</span>); <span class="fu">points</span>(mob_pnts, <span class="at">bg =</span> <span class="fu">alpha</span>(<span class="st">&quot;violet&quot;</span>, <span class="fl">0.5</span>), <span class="at">pch =</span> <span class="dv">22</span>, <span class="at">cex =</span> <span class="dv">1</span>); <span class="fu">points</span>(gr_pnts, <span class="at">bg =</span> <span class="fu">alpha</span>(<span class="st">&quot;gold&quot;</span>, <span class="fl">0.8</span>), <span class="at">pch =</span> <span class="dv">24</span>, <span class="at">cex =</span> <span class="dv">1</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<p>We have now the matching IDs with the minimum spatiotemporal distances between the grave individuals and the mobility estimates. In some instances, we have more than 1 match. In this case, I will take the average mobility estimate across the matched ones.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="burial-data.html#cb13-1" tabindex="-1"></a><span class="co"># Extract human mobility value</span></span>
<span id="cb13-2"><a href="burial-data.html#cb13-2" tabindex="-1"></a><span class="co"># MDS based</span></span>
<span id="cb13-3"><a href="burial-data.html#cb13-3" tabindex="-1"></a>ov_mds <span class="ot">&lt;-</span> <span class="fu">pblapply</span>(ids, <span class="cf">function</span>(x){</span>
<span id="cb13-4"><a href="burial-data.html#cb13-4" tabindex="-1"></a>  d <span class="ot">&lt;-</span> mobility[Sample_ID <span class="sc">%in%</span> x]</span>
<span id="cb13-5"><a href="burial-data.html#cb13-5" tabindex="-1"></a>  <span class="cf">if</span>(<span class="fu">nrow</span>(d) <span class="sc">&gt;</span> <span class="dv">1</span>){</span>
<span id="cb13-6"><a href="burial-data.html#cb13-6" tabindex="-1"></a>    <span class="fu">return</span>(<span class="fu">mean</span>(d<span class="sc">$</span>ov_dist_mds2_retro_default, <span class="at">na.rm =</span> T))</span>
<span id="cb13-7"><a href="burial-data.html#cb13-7" tabindex="-1"></a>  } <span class="cf">else</span> {</span>
<span id="cb13-8"><a href="burial-data.html#cb13-8" tabindex="-1"></a>    <span class="fu">return</span>(d<span class="sc">$</span>ov_dist_mds2_retro_default)</span>
<span id="cb13-9"><a href="burial-data.html#cb13-9" tabindex="-1"></a>  }</span>
<span id="cb13-10"><a href="burial-data.html#cb13-10" tabindex="-1"></a>})</span>
<span id="cb13-11"><a href="burial-data.html#cb13-11" tabindex="-1"></a>ov_mds <span class="ot">&lt;-</span> <span class="fu">lapply</span>(ov_mds, <span class="cf">function</span>(x) <span class="fu">ifelse</span>(<span class="fu">length</span>(x) <span class="sc">&gt;</span> <span class="dv">0</span>, x, <span class="cn">NA</span>))</span>
<span id="cb13-12"><a href="burial-data.html#cb13-12" tabindex="-1"></a></span>
<span id="cb13-13"><a href="burial-data.html#cb13-13" tabindex="-1"></a><span class="co"># PCA based</span></span>
<span id="cb13-14"><a href="burial-data.html#cb13-14" tabindex="-1"></a>ov_pca <span class="ot">&lt;-</span> <span class="fu">pblapply</span>(ids, <span class="cf">function</span>(x){</span>
<span id="cb13-15"><a href="burial-data.html#cb13-15" tabindex="-1"></a>  d <span class="ot">&lt;-</span> mobility[Sample_ID <span class="sc">%in%</span> x]</span>
<span id="cb13-16"><a href="burial-data.html#cb13-16" tabindex="-1"></a>  <span class="cf">if</span>(<span class="fu">nrow</span>(d) <span class="sc">&gt;</span> <span class="dv">1</span>){</span>
<span id="cb13-17"><a href="burial-data.html#cb13-17" tabindex="-1"></a>    <span class="fu">return</span>(<span class="fu">mean</span>(d<span class="sc">$</span>ov_dist_pca5_retro_default, <span class="at">na.rm =</span> T))</span>
<span id="cb13-18"><a href="burial-data.html#cb13-18" tabindex="-1"></a>  } <span class="cf">else</span> {</span>
<span id="cb13-19"><a href="burial-data.html#cb13-19" tabindex="-1"></a>    <span class="fu">return</span>(d<span class="sc">$</span>ov_dist_pca5_retro_default)</span>
<span id="cb13-20"><a href="burial-data.html#cb13-20" tabindex="-1"></a>  }</span>
<span id="cb13-21"><a href="burial-data.html#cb13-21" tabindex="-1"></a>})</span>
<span id="cb13-22"><a href="burial-data.html#cb13-22" tabindex="-1"></a>ov_pca <span class="ot">&lt;-</span> <span class="fu">lapply</span>(ov_pca, <span class="cf">function</span>(x) <span class="fu">ifelse</span>(<span class="fu">length</span>(x) <span class="sc">&gt;</span> <span class="dv">0</span>, x, <span class="cn">NA</span>))</span></code></pre></div>
<p>We need to acknowledge that in some cases the spatiotemporal distance could be very wide, which could create some bias during the analysis. This results from individuals that have no close match in space or time, or in spacetime, leading to choose the least distant. Here we can see a plot of the distribution of the calculated spatiotemporal distances:</p>
<div id="radius-approach" class="section level3 hasAnchor" number="1.5.1">
<h3><span class="header-section-number">1.5.1</span> Radius approach<a href="burial-data.html#radius-approach" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Here we extract 3-4 closest individuals within a 350 km radius and up to 300 years apart. If there is only 1 individual, I take the value for that one. If there are two, I take the average mobility value for those two, same for up to 4 individuals.</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="burial-data.html#cb14-1" tabindex="-1"></a>d <span class="ot">&lt;-</span> <span class="fu">apply</span>(spatdists, <span class="dv">1</span>, <span class="cf">function</span>(x) <span class="fu">which</span>(x <span class="sc">&lt;=</span> <span class="dv">350</span>))</span>
<span id="cb14-2"><a href="burial-data.html#cb14-2" tabindex="-1"></a>t <span class="ot">&lt;-</span> <span class="fu">apply</span>(tempdists, <span class="dv">1</span>, <span class="cf">function</span>(x) <span class="fu">which</span>(x <span class="sc">&lt;=</span> <span class="dv">300</span>))</span>
<span id="cb14-3"><a href="burial-data.html#cb14-3" tabindex="-1"></a></span>
<span id="cb14-4"><a href="burial-data.html#cb14-4" tabindex="-1"></a>prod <span class="ot">&lt;-</span> <span class="fu">lapply</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(d), <span class="cf">function</span>(x) <span class="fu">which</span>(d[[x]] <span class="sc">%in%</span> t[[x]])) <span class="co"># match between spat and temp</span></span>
<span id="cb14-5"><a href="burial-data.html#cb14-5" tabindex="-1"></a>prod_idx <span class="ot">&lt;-</span> <span class="fu">lapply</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(prod), <span class="cf">function</span>(x) d[[x]][prod[[x]]]) <span class="co"># get index</span></span>
<span id="cb14-6"><a href="burial-data.html#cb14-6" tabindex="-1"></a><span class="co"># Sort distances to get the smallest within the 400 km+yrs spatiotemporal radius</span></span>
<span id="cb14-7"><a href="burial-data.html#cb14-7" tabindex="-1"></a>dists <span class="ot">&lt;-</span> <span class="fu">lapply</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(prod_idx), <span class="cf">function</span>(i) {</span>
<span id="cb14-8"><a href="burial-data.html#cb14-8" tabindex="-1"></a>  v <span class="ot">&lt;-</span> st_dists[i, prod_idx[[i]]]</span>
<span id="cb14-9"><a href="burial-data.html#cb14-9" tabindex="-1"></a>  <span class="fu">names</span>(v) <span class="ot">&lt;-</span> prod_idx[[i]]</span>
<span id="cb14-10"><a href="burial-data.html#cb14-10" tabindex="-1"></a>  <span class="fu">return</span>(<span class="fu">sort</span>(v))</span>
<span id="cb14-11"><a href="burial-data.html#cb14-11" tabindex="-1"></a>  })</span>
<span id="cb14-12"><a href="burial-data.html#cb14-12" tabindex="-1"></a></span>
<span id="cb14-13"><a href="burial-data.html#cb14-13" tabindex="-1"></a>mob_ids <span class="ot">&lt;-</span> <span class="fu">lapply</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(dists), <span class="cf">function</span>(x){</span>
<span id="cb14-14"><a href="burial-data.html#cb14-14" tabindex="-1"></a>  <span class="cf">if</span>(<span class="fu">length</span>(dists[[x]]) <span class="sc">&gt;=</span> <span class="dv">1</span>){</span>
<span id="cb14-15"><a href="burial-data.html#cb14-15" tabindex="-1"></a>    ix <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">names</span>(dists[[x]]))[<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>]</span>
<span id="cb14-16"><a href="burial-data.html#cb14-16" tabindex="-1"></a>    ix <span class="ot">&lt;-</span> ix[<span class="sc">!</span><span class="fu">is.na</span>(ix)]</span>
<span id="cb14-17"><a href="burial-data.html#cb14-17" tabindex="-1"></a>    <span class="fu">return</span>(mobility<span class="sc">$</span>Sample_ID[ix])</span>
<span id="cb14-18"><a href="burial-data.html#cb14-18" tabindex="-1"></a>  } <span class="cf">else</span> {</span>
<span id="cb14-19"><a href="burial-data.html#cb14-19" tabindex="-1"></a>    <span class="fu">return</span>(<span class="cn">NA</span>)</span>
<span id="cb14-20"><a href="burial-data.html#cb14-20" tabindex="-1"></a>  }</span>
<span id="cb14-21"><a href="burial-data.html#cb14-21" tabindex="-1"></a>})</span>
<span id="cb14-22"><a href="burial-data.html#cb14-22" tabindex="-1"></a></span>
<span id="cb14-23"><a href="burial-data.html#cb14-23" tabindex="-1"></a><span class="do">## Extract mobility values</span></span>
<span id="cb14-24"><a href="burial-data.html#cb14-24" tabindex="-1"></a><span class="co"># MDS</span></span>
<span id="cb14-25"><a href="burial-data.html#cb14-25" tabindex="-1"></a>mds_dist <span class="ot">&lt;-</span> <span class="fu">pbsapply</span>(mob_ids, <span class="cf">function</span>(x){</span>
<span id="cb14-26"><a href="burial-data.html#cb14-26" tabindex="-1"></a>  d <span class="ot">&lt;-</span> mobility[Sample_ID <span class="sc">%in%</span> x]</span>
<span id="cb14-27"><a href="burial-data.html#cb14-27" tabindex="-1"></a>  <span class="cf">if</span>(<span class="fu">nrow</span>(d) <span class="sc">&gt;</span> <span class="dv">1</span>){</span>
<span id="cb14-28"><a href="burial-data.html#cb14-28" tabindex="-1"></a>    <span class="fu">return</span>(<span class="fu">mean</span>(d<span class="sc">$</span>ov_dist_mds2_retro_default, <span class="at">na.rm =</span> T))</span>
<span id="cb14-29"><a href="burial-data.html#cb14-29" tabindex="-1"></a>  } <span class="cf">else</span> <span class="cf">if</span>(<span class="fu">nrow</span>(d) <span class="sc">==</span> <span class="dv">1</span>){</span>
<span id="cb14-30"><a href="burial-data.html#cb14-30" tabindex="-1"></a>    <span class="fu">return</span>(d<span class="sc">$</span>ov_dist_mds2_retro_default)</span>
<span id="cb14-31"><a href="burial-data.html#cb14-31" tabindex="-1"></a>  } <span class="cf">else</span> {</span>
<span id="cb14-32"><a href="burial-data.html#cb14-32" tabindex="-1"></a>    <span class="fu">return</span>(<span class="cn">NA</span>)</span>
<span id="cb14-33"><a href="burial-data.html#cb14-33" tabindex="-1"></a>  }</span>
<span id="cb14-34"><a href="burial-data.html#cb14-34" tabindex="-1"></a>})</span>
<span id="cb14-35"><a href="burial-data.html#cb14-35" tabindex="-1"></a></span>
<span id="cb14-36"><a href="burial-data.html#cb14-36" tabindex="-1"></a><span class="co"># PCA</span></span>
<span id="cb14-37"><a href="burial-data.html#cb14-37" tabindex="-1"></a>pca_dist <span class="ot">&lt;-</span> <span class="fu">pbsapply</span>(mob_ids, <span class="cf">function</span>(x){</span>
<span id="cb14-38"><a href="burial-data.html#cb14-38" tabindex="-1"></a>  d <span class="ot">&lt;-</span> mobility[Sample_ID <span class="sc">%in%</span> x]</span>
<span id="cb14-39"><a href="burial-data.html#cb14-39" tabindex="-1"></a>  <span class="cf">if</span>(<span class="fu">nrow</span>(d) <span class="sc">&gt;</span> <span class="dv">1</span>){</span>
<span id="cb14-40"><a href="burial-data.html#cb14-40" tabindex="-1"></a>    <span class="fu">return</span>(<span class="fu">mean</span>(d<span class="sc">$</span>ov_dist_pca5_retro_default, <span class="at">na.rm =</span> T))</span>
<span id="cb14-41"><a href="burial-data.html#cb14-41" tabindex="-1"></a>  } <span class="cf">else</span> <span class="cf">if</span>(<span class="fu">nrow</span>(d) <span class="sc">==</span> <span class="dv">1</span>){</span>
<span id="cb14-42"><a href="burial-data.html#cb14-42" tabindex="-1"></a>    <span class="fu">return</span>(d<span class="sc">$</span>ov_dist_pca5_retro_default)</span>
<span id="cb14-43"><a href="burial-data.html#cb14-43" tabindex="-1"></a>  } <span class="cf">else</span> {</span>
<span id="cb14-44"><a href="burial-data.html#cb14-44" tabindex="-1"></a>    <span class="fu">return</span>(<span class="cn">NA</span>)</span>
<span id="cb14-45"><a href="burial-data.html#cb14-45" tabindex="-1"></a>  }</span>
<span id="cb14-46"><a href="burial-data.html#cb14-46" tabindex="-1"></a>})</span>
<span id="cb14-47"><a href="burial-data.html#cb14-47" tabindex="-1"></a></span>
<span id="cb14-48"><a href="burial-data.html#cb14-48" tabindex="-1"></a><span class="do">## Add to table</span></span>
<span id="cb14-49"><a href="burial-data.html#cb14-49" tabindex="-1"></a>miss<span class="sc">$</span>ov_dist_mds2_retro_default <span class="ot">&lt;-</span> ov_mds</span>
<span id="cb14-50"><a href="burial-data.html#cb14-50" tabindex="-1"></a>miss<span class="sc">$</span>ov_dist_pca5_retro_default <span class="ot">&lt;-</span> ov_pca</span>
<span id="cb14-51"><a href="burial-data.html#cb14-51" tabindex="-1"></a>miss<span class="sc">$</span>mobility_MDS_method2 <span class="ot">&lt;-</span> mds_dist</span>
<span id="cb14-52"><a href="burial-data.html#cb14-52" tabindex="-1"></a>miss<span class="sc">$</span>mobility_PCA_method2 <span class="ot">&lt;-</span> pca_dist</span>
<span id="cb14-53"><a href="burial-data.html#cb14-53" tabindex="-1"></a></span>
<span id="cb14-54"><a href="burial-data.html#cb14-54" tabindex="-1"></a><span class="do">## Fill gaps in graves table</span></span>
<span id="cb14-55"><a href="burial-data.html#cb14-55" tabindex="-1"></a>graves[, MobilityMatch_distance <span class="sc">:=</span> <span class="fu">as.numeric</span>(<span class="cn">NA</span>)]</span>
<span id="cb14-56"><a href="burial-data.html#cb14-56" tabindex="-1"></a>graves[Num <span class="sc">%in%</span> miss<span class="sc">$</span>Num]<span class="sc">$</span>MobilityMatch_distance <span class="ot">&lt;-</span> min_dists</span>
<span id="cb14-57"><a href="burial-data.html#cb14-57" tabindex="-1"></a>graves[Num <span class="sc">%in%</span> miss<span class="sc">$</span>Num]<span class="sc">$</span>ov_dist_mds2_retro_default <span class="ot">&lt;-</span> <span class="fu">unlist</span>(ov_mds)</span>
<span id="cb14-58"><a href="burial-data.html#cb14-58" tabindex="-1"></a>graves[Num <span class="sc">%in%</span> miss<span class="sc">$</span>Num]<span class="sc">$</span>ov_dist_pca5_retro_default <span class="ot">&lt;-</span> <span class="fu">unlist</span>(ov_pca)</span>
<span id="cb14-59"><a href="burial-data.html#cb14-59" tabindex="-1"></a>graves[, mobility_MDS_method2 <span class="sc">:=</span> <span class="fu">as.numeric</span>(<span class="cn">NA</span>)]</span>
<span id="cb14-60"><a href="burial-data.html#cb14-60" tabindex="-1"></a>graves[, mobility_PCA_method2 <span class="sc">:=</span> <span class="fu">as.numeric</span>(<span class="cn">NA</span>)]</span>
<span id="cb14-61"><a href="burial-data.html#cb14-61" tabindex="-1"></a>graves[miss<span class="sc">$</span>Num,]<span class="sc">$</span>mobility_MDS_method2 <span class="ot">&lt;-</span> miss<span class="sc">$</span>mobility_MDS_method2</span>
<span id="cb14-62"><a href="burial-data.html#cb14-62" tabindex="-1"></a>graves[miss<span class="sc">$</span>Num,]<span class="sc">$</span>mobility_PCA_method2 <span class="ot">&lt;-</span> miss<span class="sc">$</span>mobility_PCA_method2</span></code></pre></div>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="burial-data.html#cb15-1" tabindex="-1"></a><span class="fu">summary</span>(graves<span class="sc">$</span>MobilityMatch_distance)</span></code></pre></div>
<pre><code>##     Min.  1st Qu.   Median     Mean  3rd Qu.     Max.     NA&#39;s 
##     0.00    54.49    79.24   160.64   135.67 17375.57      741</code></pre>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="burial-data.html#cb17-1" tabindex="-1"></a><span class="fu">hist</span>(graves<span class="sc">$</span>MobilityMatch_distance, <span class="at">breaks =</span> <span class="dv">100</span>, <span class="at">main =</span> <span class="st">&quot;Spatiotemporal distance between grave and mobility individuals&quot;</span>, <span class="at">xlab =</span> <span class="st">&quot;Distance&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="burial-data.html#cb18-1" tabindex="-1"></a><span class="co"># How many individuals with distance &gt; 500</span></span>
<span id="cb18-2"><a href="burial-data.html#cb18-2" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">which</span>(graves<span class="sc">$</span>MobilityMatch_distance <span class="sc">&gt;</span> <span class="dv">500</span>))</span></code></pre></div>
<pre><code>## [1] 213</code></pre>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="burial-data.html#cb20-1" tabindex="-1"></a><span class="co"># How many individuals with distance &gt; 5000</span></span>
<span id="cb20-2"><a href="burial-data.html#cb20-2" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">which</span>(graves<span class="sc">$</span>MobilityMatch_distance <span class="sc">&gt;</span> <span class="dv">5000</span>))</span></code></pre></div>
<pre><code>## [1] 1</code></pre>
<p>We have one individual that has a very large spatiotemporal distance. This is due to the age of the grave (YearBP = 25693), being very old. The oldest age of the individuals with mobility estimates is 9214. This creates a combined spatiotemporal distance that is very large. We can discuss whether it would be a good idea to <strong>discard</strong> this grave.</p>
<p>At least, we have few individuals that show very big spatiotemporal distances. We can maybe decide later on if we should put a distance threshold.</p>
<p>Now we do the same for ancestry values.</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="burial-data.html#cb22-1" tabindex="-1"></a><span class="co"># Subset data to individuals with no estimates of ancestry</span></span>
<span id="cb22-2"><a href="burial-data.html#cb22-2" tabindex="-1"></a>miss <span class="ot">&lt;-</span> graves[<span class="fu">is.na</span>(ANCE1)]</span>
<span id="cb22-3"><a href="burial-data.html#cb22-3" tabindex="-1"></a><span class="co"># Remove individuals for which we do not have an age</span></span>
<span id="cb22-4"><a href="burial-data.html#cb22-4" tabindex="-1"></a>miss <span class="ot">&lt;-</span> miss[<span class="sc">!</span><span class="fu">is.na</span>(YearBP)]</span>
<span id="cb22-5"><a href="burial-data.html#cb22-5" tabindex="-1"></a></span>
<span id="cb22-6"><a href="burial-data.html#cb22-6" tabindex="-1"></a><span class="co"># Transform to points</span></span>
<span id="cb22-7"><a href="burial-data.html#cb22-7" tabindex="-1"></a>gr_pnts <span class="ot">&lt;-</span> <span class="fu">project</span>(<span class="fu">vect</span>(<span class="at">x =</span> miss[, .(Longitude, Latitude, aDNAID, Num, YearBP)],</span>
<span id="cb22-8"><a href="burial-data.html#cb22-8" tabindex="-1"></a>                        <span class="at">geom =</span> <span class="fu">c</span>(<span class="st">&quot;Longitude&quot;</span>, <span class="st">&quot;Latitude&quot;</span>), <span class="at">crs =</span> <span class="fu">crs</span>(<span class="fu">rast</span>())),</span>
<span id="cb22-9"><a href="burial-data.html#cb22-9" tabindex="-1"></a>                   proj)</span>
<span id="cb22-10"><a href="burial-data.html#cb22-10" tabindex="-1"></a>ance_pnts <span class="ot">&lt;-</span> <span class="fu">project</span>(<span class="fu">vect</span>(ancestry[, .(LON, LAT, IND, TIME)], </span>
<span id="cb22-11"><a href="burial-data.html#cb22-11" tabindex="-1"></a>                          <span class="at">geom =</span> <span class="fu">c</span>(<span class="st">&quot;LON&quot;</span>, <span class="st">&quot;LAT&quot;</span>),</span>
<span id="cb22-12"><a href="burial-data.html#cb22-12" tabindex="-1"></a>                          <span class="at">crs =</span> <span class="fu">crs</span>(<span class="fu">rast</span>())),</span>
<span id="cb22-13"><a href="burial-data.html#cb22-13" tabindex="-1"></a>                     proj)</span></code></pre></div>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="burial-data.html#cb23-1" tabindex="-1"></a><span class="fu">plot</span>(ance_pnts, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>); <span class="fu">points</span>(gr_pnts, <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>); <span class="fu">plot</span>(conts_prj, <span class="at">add =</span> T)</span></code></pre></div>
<p>We are going to do the same as before.</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="burial-data.html#cb24-1" tabindex="-1"></a><span class="do">## Method 1: minimum spatiotemporal distance</span></span>
<span id="cb24-2"><a href="burial-data.html#cb24-2" tabindex="-1"></a><span class="co"># Calculate euclidean distance in space</span></span>
<span id="cb24-3"><a href="burial-data.html#cb24-3" tabindex="-1"></a>spatdists <span class="ot">&lt;-</span> <span class="fu">distance</span>(gr_pnts, ance_pnts, <span class="at">unit =</span> <span class="st">&quot;km&quot;</span>)</span>
<span id="cb24-4"><a href="burial-data.html#cb24-4" tabindex="-1"></a></span>
<span id="cb24-5"><a href="burial-data.html#cb24-5" tabindex="-1"></a><span class="co"># Calculate euclidean distance in time</span></span>
<span id="cb24-6"><a href="burial-data.html#cb24-6" tabindex="-1"></a>pairs <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(gr_pnts<span class="sc">$</span>YearBP, ance_pnts<span class="sc">$</span>TIME)</span>
<span id="cb24-7"><a href="burial-data.html#cb24-7" tabindex="-1"></a>tempdists <span class="ot">&lt;-</span> <span class="fu">apply</span>(pairs, <span class="dv">1</span>, <span class="cf">function</span>(r) <span class="fu">sqrt</span>(<span class="fu">sum</span>((r[<span class="dv">1</span>] <span class="sc">-</span> r[<span class="dv">2</span>])<span class="sc">^</span><span class="dv">2</span>)))</span>
<span id="cb24-8"><a href="burial-data.html#cb24-8" tabindex="-1"></a>tempdists <span class="ot">&lt;-</span> <span class="fu">matrix</span>(tempdists, </span>
<span id="cb24-9"><a href="burial-data.html#cb24-9" tabindex="-1"></a>                    <span class="at">nrow =</span> <span class="fu">length</span>(gr_pnts<span class="sc">$</span>YearBP), </span>
<span id="cb24-10"><a href="burial-data.html#cb24-10" tabindex="-1"></a>                    <span class="at">ncol =</span> <span class="fu">length</span>(ance_pnts<span class="sc">$</span>TIME))</span>
<span id="cb24-11"><a href="burial-data.html#cb24-11" tabindex="-1"></a></span>
<span id="cb24-12"><a href="burial-data.html#cb24-12" tabindex="-1"></a><span class="co"># spatiotemporal distances (euclidean with km == year)</span></span>
<span id="cb24-13"><a href="burial-data.html#cb24-13" tabindex="-1"></a>st_dists <span class="ot">&lt;-</span> <span class="fu">sqrt</span>((spatdists <span class="sc">+</span> tempdists)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb24-14"><a href="burial-data.html#cb24-14" tabindex="-1"></a></span>
<span id="cb24-15"><a href="burial-data.html#cb24-15" tabindex="-1"></a><span class="co"># Find minimum spatial distance</span></span>
<span id="cb24-16"><a href="burial-data.html#cb24-16" tabindex="-1"></a>min_columns <span class="ot">&lt;-</span> <span class="fu">apply</span>(st_dists, <span class="dv">1</span>, find_min)</span>
<span id="cb24-17"><a href="burial-data.html#cb24-17" tabindex="-1"></a>min_dists <span class="ot">&lt;-</span> <span class="fu">apply</span>(st_dists, <span class="dv">1</span>, min)</span>
<span id="cb24-18"><a href="burial-data.html#cb24-18" tabindex="-1"></a></span>
<span id="cb24-19"><a href="burial-data.html#cb24-19" tabindex="-1"></a><span class="co"># Get individual ID from ancestry table</span></span>
<span id="cb24-20"><a href="burial-data.html#cb24-20" tabindex="-1"></a>ids <span class="ot">&lt;-</span> <span class="fu">lapply</span>(min_columns, <span class="cf">function</span>(x) ancestry<span class="sc">$</span>IND[x])</span>
<span id="cb24-21"><a href="burial-data.html#cb24-21" tabindex="-1"></a></span>
<span id="cb24-22"><a href="burial-data.html#cb24-22" tabindex="-1"></a><span class="co"># Extract ancestry value</span></span>
<span id="cb24-23"><a href="burial-data.html#cb24-23" tabindex="-1"></a>ance <span class="ot">&lt;-</span> <span class="fu">paste0</span>(<span class="st">&quot;ANCE&quot;</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">9</span>)</span>
<span id="cb24-24"><a href="burial-data.html#cb24-24" tabindex="-1"></a>anc_vals <span class="ot">&lt;-</span> <span class="fu">rbindlist</span>(<span class="fu">pblapply</span>(ids, <span class="cf">function</span>(x){</span>
<span id="cb24-25"><a href="burial-data.html#cb24-25" tabindex="-1"></a>  d <span class="ot">&lt;-</span> ancestry[IND <span class="sc">%in%</span> x]</span>
<span id="cb24-26"><a href="burial-data.html#cb24-26" tabindex="-1"></a>  <span class="cf">if</span>(<span class="fu">nrow</span>(d) <span class="sc">&gt;</span> <span class="dv">1</span>){</span>
<span id="cb24-27"><a href="burial-data.html#cb24-27" tabindex="-1"></a>    <span class="fu">return</span>(<span class="fu">as.data.table</span>(<span class="fu">matrix</span>(<span class="fu">colMeans</span>(d[, ..ance], <span class="at">na.rm =</span> T), <span class="at">nrow =</span> <span class="dv">1</span>, <span class="at">dimnames =</span> <span class="fu">list</span>(<span class="cn">NULL</span>, ance))))</span>
<span id="cb24-28"><a href="burial-data.html#cb24-28" tabindex="-1"></a>  } <span class="cf">else</span> {</span>
<span id="cb24-29"><a href="burial-data.html#cb24-29" tabindex="-1"></a>    <span class="fu">return</span>(d[, ..ance])</span>
<span id="cb24-30"><a href="burial-data.html#cb24-30" tabindex="-1"></a>  }</span>
<span id="cb24-31"><a href="burial-data.html#cb24-31" tabindex="-1"></a>}))</span>
<span id="cb24-32"><a href="burial-data.html#cb24-32" tabindex="-1"></a></span>
<span id="cb24-33"><a href="burial-data.html#cb24-33" tabindex="-1"></a><span class="do">## Method 2: average across the 4 closest individuals within a 350 km and 300 years radius. This threshold has been chosen to minimize the loss of data (only 16% now are not paired with an ancestry value)</span></span>
<span id="cb24-34"><a href="burial-data.html#cb24-34" tabindex="-1"></a>d <span class="ot">&lt;-</span> <span class="fu">apply</span>(spatdists, <span class="dv">1</span>, <span class="cf">function</span>(x) <span class="fu">which</span>(x <span class="sc">&lt;=</span> <span class="dv">350</span>))</span>
<span id="cb24-35"><a href="burial-data.html#cb24-35" tabindex="-1"></a>t <span class="ot">&lt;-</span> <span class="fu">apply</span>(tempdists, <span class="dv">1</span>, <span class="cf">function</span>(x) <span class="fu">which</span>(x <span class="sc">&lt;=</span> <span class="dv">300</span>))</span>
<span id="cb24-36"><a href="burial-data.html#cb24-36" tabindex="-1"></a></span>
<span id="cb24-37"><a href="burial-data.html#cb24-37" tabindex="-1"></a>prod <span class="ot">&lt;-</span> <span class="fu">lapply</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(d), <span class="cf">function</span>(x) <span class="fu">which</span>(d[[x]] <span class="sc">%in%</span> t[[x]])) <span class="co"># match between spat and temp</span></span>
<span id="cb24-38"><a href="burial-data.html#cb24-38" tabindex="-1"></a>prod_idx <span class="ot">&lt;-</span> <span class="fu">lapply</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(prod), <span class="cf">function</span>(x) d[[x]][prod[[x]]]) <span class="co"># get index</span></span>
<span id="cb24-39"><a href="burial-data.html#cb24-39" tabindex="-1"></a><span class="co"># Sort distances to get the smallest within the spatiotemporal radius</span></span>
<span id="cb24-40"><a href="burial-data.html#cb24-40" tabindex="-1"></a>dists <span class="ot">&lt;-</span> <span class="fu">lapply</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(prod_idx), <span class="cf">function</span>(i) {</span>
<span id="cb24-41"><a href="burial-data.html#cb24-41" tabindex="-1"></a>  v <span class="ot">&lt;-</span> st_dists[i, prod_idx[[i]]]</span>
<span id="cb24-42"><a href="burial-data.html#cb24-42" tabindex="-1"></a>  <span class="fu">names</span>(v) <span class="ot">&lt;-</span> prod_idx[[i]]</span>
<span id="cb24-43"><a href="burial-data.html#cb24-43" tabindex="-1"></a>  <span class="fu">return</span>(<span class="fu">sort</span>(v))</span>
<span id="cb24-44"><a href="burial-data.html#cb24-44" tabindex="-1"></a>  })</span>
<span id="cb24-45"><a href="burial-data.html#cb24-45" tabindex="-1"></a></span>
<span id="cb24-46"><a href="burial-data.html#cb24-46" tabindex="-1"></a>ance_ids <span class="ot">&lt;-</span> <span class="fu">lapply</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(dists), <span class="cf">function</span>(x){</span>
<span id="cb24-47"><a href="burial-data.html#cb24-47" tabindex="-1"></a>  <span class="cf">if</span>(<span class="fu">length</span>(dists[[x]]) <span class="sc">&gt;=</span> <span class="dv">1</span>){</span>
<span id="cb24-48"><a href="burial-data.html#cb24-48" tabindex="-1"></a>    ix <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">names</span>(dists[[x]]))[<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>]</span>
<span id="cb24-49"><a href="burial-data.html#cb24-49" tabindex="-1"></a>    ix <span class="ot">&lt;-</span> ix[<span class="sc">!</span><span class="fu">is.na</span>(ix)]</span>
<span id="cb24-50"><a href="burial-data.html#cb24-50" tabindex="-1"></a>    <span class="fu">return</span>(ancestry<span class="sc">$</span>IND[ix])</span>
<span id="cb24-51"><a href="burial-data.html#cb24-51" tabindex="-1"></a>  } <span class="cf">else</span> {</span>
<span id="cb24-52"><a href="burial-data.html#cb24-52" tabindex="-1"></a>    <span class="fu">return</span>(<span class="cn">NA</span>)</span>
<span id="cb24-53"><a href="burial-data.html#cb24-53" tabindex="-1"></a>  }</span>
<span id="cb24-54"><a href="burial-data.html#cb24-54" tabindex="-1"></a>})</span>
<span id="cb24-55"><a href="burial-data.html#cb24-55" tabindex="-1"></a></span>
<span id="cb24-56"><a href="burial-data.html#cb24-56" tabindex="-1"></a><span class="do">## Extract ancestry values</span></span>
<span id="cb24-57"><a href="burial-data.html#cb24-57" tabindex="-1"></a>ance_lookup <span class="ot">&lt;-</span> ancestry[, .(IND, ANCE1, ANCE2, ANCE3, ANCE4, ANCE5, ANCE6, ANCE7, ANCE8, ANCE9)]</span>
<span id="cb24-58"><a href="burial-data.html#cb24-58" tabindex="-1"></a>ance_v2 <span class="ot">&lt;-</span> <span class="fu">rbindlist</span>(<span class="fu">pblapply</span>(ance_ids, <span class="cf">function</span>(x){</span>
<span id="cb24-59"><a href="burial-data.html#cb24-59" tabindex="-1"></a>  d <span class="ot">&lt;-</span> ance_lookup[IND <span class="sc">%in%</span> x]</span>
<span id="cb24-60"><a href="burial-data.html#cb24-60" tabindex="-1"></a>  <span class="cf">if</span>(<span class="fu">nrow</span>(d) <span class="sc">&gt;</span> <span class="dv">1</span>){</span>
<span id="cb24-61"><a href="burial-data.html#cb24-61" tabindex="-1"></a>    <span class="fu">return</span>(<span class="fu">as.data.table</span>(<span class="fu">matrix</span>(<span class="fu">colMeans</span>(d[, ..ance], <span class="at">na.rm =</span> T), <span class="at">nrow =</span> <span class="dv">1</span>, <span class="at">dimnames =</span> <span class="fu">list</span>(<span class="cn">NULL</span>, ance))))</span>
<span id="cb24-62"><a href="burial-data.html#cb24-62" tabindex="-1"></a>  } <span class="cf">else</span> <span class="cf">if</span>(<span class="fu">nrow</span>(d) <span class="sc">==</span> <span class="dv">1</span>){</span>
<span id="cb24-63"><a href="burial-data.html#cb24-63" tabindex="-1"></a>    <span class="fu">return</span>(d[, ..ance])</span>
<span id="cb24-64"><a href="burial-data.html#cb24-64" tabindex="-1"></a>  } <span class="cf">else</span> {</span>
<span id="cb24-65"><a href="burial-data.html#cb24-65" tabindex="-1"></a>    <span class="fu">return</span>(<span class="fu">data.table</span>(<span class="at">ANCE1 =</span> <span class="fu">as.numeric</span>(<span class="cn">NA</span>), </span>
<span id="cb24-66"><a href="burial-data.html#cb24-66" tabindex="-1"></a>                      <span class="at">ANCE2 =</span> <span class="fu">as.numeric</span>(<span class="cn">NA</span>), </span>
<span id="cb24-67"><a href="burial-data.html#cb24-67" tabindex="-1"></a>                      <span class="at">ANCE3 =</span> <span class="fu">as.numeric</span>(<span class="cn">NA</span>), </span>
<span id="cb24-68"><a href="burial-data.html#cb24-68" tabindex="-1"></a>                      <span class="at">ANCE4 =</span> <span class="fu">as.numeric</span>(<span class="cn">NA</span>), </span>
<span id="cb24-69"><a href="burial-data.html#cb24-69" tabindex="-1"></a>                      <span class="at">ANCE5 =</span> <span class="fu">as.numeric</span>(<span class="cn">NA</span>), </span>
<span id="cb24-70"><a href="burial-data.html#cb24-70" tabindex="-1"></a>                      <span class="at">ANCE6 =</span> <span class="fu">as.numeric</span>(<span class="cn">NA</span>), </span>
<span id="cb24-71"><a href="burial-data.html#cb24-71" tabindex="-1"></a>                      <span class="at">ANCE7 =</span> <span class="fu">as.numeric</span>(<span class="cn">NA</span>), </span>
<span id="cb24-72"><a href="burial-data.html#cb24-72" tabindex="-1"></a>                      <span class="at">ANCE8 =</span> <span class="fu">as.numeric</span>(<span class="cn">NA</span>), </span>
<span id="cb24-73"><a href="burial-data.html#cb24-73" tabindex="-1"></a>                      <span class="at">ANCE9 =</span> <span class="fu">as.numeric</span>(<span class="cn">NA</span>)))</span>
<span id="cb24-74"><a href="burial-data.html#cb24-74" tabindex="-1"></a>  }</span>
<span id="cb24-75"><a href="burial-data.html#cb24-75" tabindex="-1"></a>}))</span>
<span id="cb24-76"><a href="burial-data.html#cb24-76" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">which</span>(<span class="fu">is.na</span>(ance_v2<span class="sc">$</span>ANCE1)))<span class="sc">/</span><span class="fu">nrow</span>(ance_v2) <span class="co"># 16% NAs</span></span>
<span id="cb24-77"><a href="burial-data.html#cb24-77" tabindex="-1"></a></span>
<span id="cb24-78"><a href="burial-data.html#cb24-78" tabindex="-1"></a><span class="co"># Create table of ancestry values</span></span>
<span id="cb24-79"><a href="burial-data.html#cb24-79" tabindex="-1"></a>anc_vals[, Num <span class="sc">:=</span> miss<span class="sc">$</span>Num]</span>
<span id="cb24-80"><a href="burial-data.html#cb24-80" tabindex="-1"></a><span class="fu">names</span>(ance_v2) <span class="ot">&lt;-</span> <span class="fu">paste0</span>(<span class="fu">names</span>(ance_v2), <span class="st">&quot;_v2&quot;</span>)</span>
<span id="cb24-81"><a href="burial-data.html#cb24-81" tabindex="-1"></a>ance_v2[, Num <span class="sc">:=</span> miss<span class="sc">$</span>Num]</span>
<span id="cb24-82"><a href="burial-data.html#cb24-82" tabindex="-1"></a></span>
<span id="cb24-83"><a href="burial-data.html#cb24-83" tabindex="-1"></a><span class="co"># Add minimum distance between grave individuals and ancestry individuals</span></span>
<span id="cb24-84"><a href="burial-data.html#cb24-84" tabindex="-1"></a>graves[, AncestryMatch_distance <span class="sc">:=</span> <span class="fu">as.numeric</span>(<span class="cn">NA</span>)]</span>
<span id="cb24-85"><a href="burial-data.html#cb24-85" tabindex="-1"></a>graves[miss<span class="sc">$</span>Num,]<span class="sc">$</span>AncestryMatch_distance <span class="ot">&lt;-</span> min_dists</span>
<span id="cb24-86"><a href="burial-data.html#cb24-86" tabindex="-1"></a></span>
<span id="cb24-87"><a href="burial-data.html#cb24-87" tabindex="-1"></a><span class="co"># Fill the gaps</span></span>
<span id="cb24-88"><a href="burial-data.html#cb24-88" tabindex="-1"></a><span class="cf">for</span>(a <span class="cf">in</span> ance){</span>
<span id="cb24-89"><a href="burial-data.html#cb24-89" tabindex="-1"></a>  graves[anc_vals<span class="sc">$</span>Num, a] <span class="ot">&lt;-</span> anc_vals[, ..a]</span>
<span id="cb24-90"><a href="burial-data.html#cb24-90" tabindex="-1"></a>}</span>
<span id="cb24-91"><a href="burial-data.html#cb24-91" tabindex="-1"></a>graves[, <span class="fu">names</span>(ance_v2)[<span class="sc">-</span><span class="fu">length</span>(<span class="fu">names</span>(ance_v2))] <span class="sc">:=</span> <span class="fu">as.numeric</span>(<span class="cn">NA</span>)]</span>
<span id="cb24-92"><a href="burial-data.html#cb24-92" tabindex="-1"></a>graves[ance_v2<span class="sc">$</span>Num, <span class="fu">names</span>(ance_v2)[<span class="sc">-</span><span class="fu">length</span>(<span class="fu">names</span>(ance_v2))]] <span class="ot">&lt;-</span> ance_v2[, .(ANCE1_v2, ANCE2_v2, ANCE3_v2, ANCE4_v2, ANCE5_v2, ANCE6_v2, ANCE7_v2, ANCE8_v2, ANCE9_v2)]</span></code></pre></div>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="burial-data.html#cb25-1" tabindex="-1"></a><span class="fu">summary</span>(graves<span class="sc">$</span>AncestryMatch_distance)</span></code></pre></div>
<pre><code>##      Min.   1st Qu.    Median      Mean   3rd Qu.      Max.      NA&#39;s 
##     5.057   156.762   281.138   306.257   407.073 12504.351       423</code></pre>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="burial-data.html#cb27-1" tabindex="-1"></a><span class="fu">hist</span>(graves<span class="sc">$</span>AncestryMatch_distance, <span class="at">breaks =</span> <span class="dv">100</span>, <span class="at">main =</span> <span class="st">&quot;Spatiotemporal distance between graves and ancestry&quot;</span>, <span class="at">xlab =</span> <span class="st">&quot;Distance&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="burial-data.html#cb28-1" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">which</span>(graves<span class="sc">$</span>AncestryMatch_distance <span class="sc">&gt;</span> <span class="dv">500</span>))</span></code></pre></div>
<pre><code>## [1] 479</code></pre>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="burial-data.html#cb30-1" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">which</span>(graves<span class="sc">$</span>AncestryMatch_distance <span class="sc">&gt;</span> <span class="dv">5000</span>))</span></code></pre></div>
<pre><code>## [1] 1</code></pre>
<p>We have now all the data ready to be analysed, but we still need to set up the inlabru model.</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="aim.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="burial-rites.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": "https://github.com/USERNAME/REPO/edit/BRANCH/01-Graves.Rmd",
    "text": "Edit"
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
